### ISSUE TITLE
Clarification needed: ATtiny13, ATtiny45 or ATtiny85? 

### ISSUE THREAD

**Issue by pablofrommars** [rudiratlos/RPI_PowerMgmt#1]
The schematic mentions an ATtiny13 (and an ATtiny45?) while the avrdude section mentions an ATtiny85. Can you please clarify which micro-controllers can work with your project?

Thanks for your time, this is very useful.

**Comment by rudiratlos** [comment]
85 only. program needs the rom and ram space entirly. tiny45 is to small

**Comment by pablofrommars** [comment]
Thanks for the quick reply!
