### ISSUE TITLE
Relay type

### ISSUE THREAD

**Issue by pablofrommars** [rudiratlos/RPI_PowerMgmt#2]
Thanks for your hard work, this is very useful!

Would you be able to share the types of relay you have tested in your project?

I am struggling to find appropriate ones complying with the power requirements of a Pi 4.

**Comment by rudiratlos** [comment]
we are using:
BC850 (Transistor)
1kOhm
Diode
Omron G6RN (Realais 5DC)

**Comment by rudiratlos** [comment]
Von meinem Smartphone gesendet,
Mit freundlichen Grüßen
Stefan Fischer

**Comment by pablofrommars** [comment]
Thanks so much!
